language: node_js
cache: yarn
env:
  - secure: "aP+SHRFIh/WAvtgl1g1q7/DpZ9JwCr20k1JgWq6FrVn5CqHuSAEUaNvMTCyMc6F3vkCVuJgyY6lhcv4wXL2HnVK/vyA+2A+qsOhJErPDMtJBXgyVW2Iop29sHr2rTxGMxAZ24swhT7LLiJzAfyDiA8bVwfbZmWezJR2isCE0YTX3vKF93/WhpUVENOe3twZGCz0k2vGAs4LQ/v3UmbpBQxgVyTcqey+UVquqEfsoYhSgMxyAyMcV5wvoyDSvZvKw8tQ6qP6HwFRBenGYQ/OMz9G96ubaFH7cn1iCdEkArWDZzMtFrGqLHme6WYN7xKRL4qnnmXBoiUhPj7edysqOiop8KFJHzIq3ILY3JhNuIQK4J80+V9VNBtbyWEc1umSRcBWpvDUTebia4yd/vSvHpNuHGETixA519wV9kVhA2MMaqWsI0LZdg8o329yG+uok6fFJ2QWZ9GoQLC0FwVW+Au5rQYqShYIl7jOOt5SdwvtCNMR/53JYN+LMpW8i8ftZb4tXq6TWi3hgDuo9HIECFwr6kOBhEiO9YSbMPchDQY9SGTuUNP09QBYZy9kuHffRQcju5Nk0swFKHfR8awpfFL5d8xVNLlYn/njCRhOJhiqhK5GAmliGG3ePY1RN7o3gEQWIvip91m7zu2pQTyr3HRh7t3opuqCYlq0VZf4cl6o="
before_script:
  - npm install -g gatsby-cli
node_js:
  - "12"
script:
  - yarn build
deploy:
  provider: script
  script: yarn run deploy
  skip_cleanup: true
  on:
    branch: master